# Configuration file for the Sphinx documentation builder.
# ADT - Sistema de Traducción Técnica
# Versión 1.0.0

# -- Path setup --------------------------------------------------------------

import os
import sys
sys.path.insert(0, os.path.abspath('.'))

# -- Project information -----------------------------------------------------

project = 'ADT - Procedimientos de Traducción Técnica'
copyright = '2026, Equipo ADT'
author = 'Equipo ADT'

# The full version, including alpha/beta/rc tags
release = '1.0.0'
version = '1.0'

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension names here, as strings
extensions = [
    'sphinx.ext.autodoc',           # Auto-generate documentation
    'sphinx.ext.intersphinx',       # Link to other projects' documentation
    'sphinx.ext.todo',              # Support for todo items
    'sphinx.ext.viewcode',          # Add links to highlighted source code
    'sphinx.ext.napoleon',          # Support for NumPy and Google style docstrings
    'sphinx.ext.autosectionlabel',  # Auto-generate section labels
    'sphinx_design',                # Design elements (cards, tabs, etc.)
    'sphinx_copybutton',            # Copy button for code blocks
    'sphinx_tabs.tabs',             # Tabs support
    'myst_parser',                  # Markdown support
]

# Add any paths that contain templates here
templates_path = ['_templates']

# List of patterns to ignore
exclude_patterns = []

# The language for content autogenerated by Sphinx
language = 'es'

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages
html_theme = 'furo'

# Theme options
html_theme_options = {
    "light_css_variables": {
        "color-brand-primary": "#199cd7",
        "color-brand-content": "#199cd7",
    },
    "dark_css_variables": {
        "color-brand-primary": "#4da6e0",
        "color-brand-content": "#4da6e0",
    },
    "sidebar_hide_name": False,
    "navigation_with_keys": True,
}

# Add any paths that contain custom static files
html_static_path = ['_static']

# Custom sidebar templates
html_sidebars = {
    "**": [
        "sidebar/brand.html",
        "sidebar/search.html",
        "sidebar/scroll-start.html",
        "sidebar/navigation.html",
        "sidebar/scroll-end.html",
    ]
}

# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    'papersize': 'letterpaper',
    'pointsize': '10pt',
    'preamble': '',
    'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files
latex_documents = [
    ('index', 'ADT-Traduccion.tex', 
     'ADT - Procedimientos de Traducción Técnica',
     'Equipo ADT', 'manual'),
]

# -- Options for manual page output ------------------------------------------

man_pages = [
    ('index', 'adt-traduccion', 
     'ADT - Procedimientos de Traducción Técnica',
     ['Equipo ADT'], 1)
]

# -- Options for Texinfo output ----------------------------------------------

texinfo_documents = [
    ('index', 'ADT-Traduccion', 
     'ADT - Procedimientos de Traducción Técnica',
     'Equipo ADT', 'ADT-Traduccion', 
     'Sistema de traducción técnica.',
     'Miscellaneous'),
]

# -- Extension configuration -------------------------------------------------

# sphinx.ext.autosectionlabel
autosectionlabel_prefix_document = True
autosectionlabel_maxdepth = 3

# sphinx.ext.todo
todo_include_todos = True

# sphinx.ext.intersphinx
intersphinx_mapping = {
    'python': ('https://docs.python.org/3/', None),
    'sphinx': ('https://www.sphinx-doc.org/en/master/', None),
}

# sphinx-copybutton
copybutton_prompt_text = r">>> |\.\.\. |\$ |In \[\d*\]: | {2,5}\.\.\.: | {5,8}: "
copybutton_prompt_is_regexp = True
copybutton_only_copy_prompt_lines = True

# myst_parser
myst_enable_extensions = [
    "colon_fence",
    "deflist",
    "dollarmath",
    "html_admonition",
    "html_image",
    "replacements",
    "smartquotes",
    "tasklist",
]

# -- Custom configuration ----------------------------------------------------

# Numeración de figuras y tablas
numfig = True
numfig_format = {
    'figure': 'Figura %s',
    'table': 'Tabla %s',
    'code-block': 'Listado %s',
    'section': 'Sección %s',
}

# Profundidad del TOC
html_theme_options['toc_depth'] = 3

# Mostrar fuente en documentos
html_show_sourcelink = True
html_copy_source = True

# Opciones de búsqueda
html_search_language = 'es'
html_search_options = {'type': 'default'}

# Favicon y logo (agregar archivos si existen)
# html_favicon = '_static/favicon.ico'
# html_logo = '_static/logo.png'

# Título de la página HTML
html_title = f"{project} v{version}"

# Índice corto
html_short_title = "ADT Traducción"

# Footer personalizado
html_show_copyright = True
html_show_sphinx = True

# -- Opciones de LaTeX personalizadas ----------------------------------------

latex_engine = 'pdflatex'
latex_use_xindy = False

# Elementos del documento LaTeX
latex_elements['preamble'] = r'''
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[spanish]{babel}
\usepackage{lmodern}
'''

# -- Configuración de traducción ---------------------------------------------

# Idioma del proyecto
locale_dirs = ['locale/']
gettext_compact = False

# -- Configuración personalizada ADT -----------------------------------------

# Metadatos del proyecto ADT
adt_project_info = {
    'name': 'ADT',
    'full_name': 'Arc42-Diátaxis-Traducción',
    'version': '1.0.0',
    'components': ['arc42', 'diataxis', 'traduccion', 'biblioteca'],
    'frameworks': {
        'arc42': '12 secciones arquitectónicas',
        'diataxis': '4 tipos de documentación',
        'traduccion': '10 secciones metodológicas',
    }
}

# Configuración de glosarios
glossary_term_types = ['term', 'technical-term', 'acronym', 'concept']

# Configuración de referencias
ref_patterns = {
    'procedimiento': 'PROC_\\d{3}',
    'estandar': 'STD_\\d{3}',
    'regla': 'RT_\\d{3}',
    'escenario': 'ESC_\\d{3}',
}

# Configuración de traducción
translation_config = {
    'source_language': 'en',
    'target_language': 'es-MX',
    'preserve_technical_terms': True,
    'first_appearance_format': 'español (:term:`inglés`)',
    'subsequent_format': 'español',
}
