# Configuration file for the Sphinx documentation builder.
# ADT42 - Arc-Diátaxis-Translation-42
# Sistema Integrado de Documentación Arquitectónica y Traducción Técnica

import os
import sys
sys.path.insert(0, os.path.abspath('.'))

# -- Project information -----------------------------------------------------

project = 'ADT42 - Procedimientos de Traducción Técnica'
copyright = '2026, Equipo ADT42'
author = 'Equipo ADT42'
release = '1.0.0'
version = '1.0'

# -- General configuration ---------------------------------------------------

extensions = [
    'sphinxcontrib.plantuml',
    'sphinx.ext.autodoc',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.viewcode',
    'sphinx.ext.napoleon',
    'sphinx.ext.autosectionlabel',
    'sphinx_design',
    'sphinx_copybutton',
    'sphinx_tabs.tabs',
    'myst_parser',
]

templates_path = ['_templates']
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The language for content autogenerated by Sphinx
language = 'es'

# -- Options for HTML output -------------------------------------------------

html_theme = 'furo'

html_theme_options = {
    "light_css_variables": {
        "color-brand-primary": "#199cd7",
        "color-brand-content": "#199cd7",
    },
    "dark_css_variables": {
        "color-brand-primary": "#4da6e0",
        "color-brand-content": "#4da6e0",
    },
    "sidebar_hide_name": False,
    "navigation_with_keys": True,
}

html_static_path = ['_static']

html_sidebars = {
    "**": [
        "sidebar/brand.html",
        "sidebar/search.html",
        "sidebar/scroll-start.html",
        "sidebar/navigation.html",
        "sidebar/scroll-end.html",
    ]
}

# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    'papersize': 'letterpaper',
    'pointsize': '10pt',
    'preamble': r'''
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[spanish]{babel}
\usepackage{lmodern}
''',
    'figure_align': 'htbp',
}

latex_documents = [
    ('index', 'ADT42.tex', 
     'ADT42 - Procedimientos de Traducción Técnica',
     'Equipo ADT42', 'manual'),
]

# -- Extension configuration -------------------------------------------------

# sphinx.ext.autosectionlabel
autosectionlabel_prefix_document = True
autosectionlabel_maxdepth = 3

# sphinx.ext.todo
todo_include_todos = True

# sphinx.ext.intersphinx
intersphinx_mapping = {
    'python': ('https://docs.python.org/3/', None),
    'sphinx': ('https://www.sphinx-doc.org/en/master/', None),
}

# sphinx-copybutton
copybutton_prompt_text = r">>> |\.\.\. |\$ |In \[\d*\]: | {2,5}\.\.\.: | {5,8}: "
copybutton_prompt_is_regexp = True
copybutton_only_copy_prompt_lines = True

# myst_parser
myst_enable_extensions = [
    'sphinxcontrib.plantuml',
    "colon_fence",
    "deflist",
    "dollarmath",
    "html_admonition",
    "html_image",
    "replacements",
    "smartquotes",
    "tasklist",
]

# -- Custom configuration ----------------------------------------------------

# Numeración de figuras y tablas
numfig = True
numfig_format = {
    'figure': 'Figura %s',
    'table': 'Tabla %s',
    'code-block': 'Listado %s',
    'section': 'Sección %s',
}

# Profundidad del TOC
html_theme_options['toc_depth'] = 3

# Mostrar fuente en documentos
html_show_sourcelink = True
html_copy_source = True

# Opciones de búsqueda
html_search_language = 'es'
html_search_options = {'type': 'default'}

# Título de la página HTML
html_title = f"{project} v{version}"
html_short_title = "ADT42"

# Footer
html_show_copyright = True
html_show_sphinx = True

# LaTeX
latex_engine = 'pdflatex'
latex_use_xindy = False

# Idioma del proyecto
locale_dirs = ['locale/']
gettext_compact = False

# -- Configuración personalizada ADT42 ---------------------------------------

# Metadatos del proyecto ADT42
adt42_project_info = {
    'name': 'ADT42',
    'full_name': 'Arc42-Diátaxis-Translation-42',
    'version': '1.0.0',
    'components': ['arc42', 'diataxis', 'traduccion', 'biblioteca'],
    'frameworks': {
        'arc42': '12 secciones arquitectónicas',
        'diataxis': '4 tipos de documentación',
        'traduccion': '10 secciones metodológicas',
    }
}

# Configuración de glosarios
glossary_term_types = ['term', 'technical-term', 'acronym', 'concept']

# Configuración de referencias
ref_patterns = {
    'procedimiento': 'PROC_\\d{3}',
    'estandar': 'STD_\\d{3}',
    'regla': 'RT_\\d{3}',
    'escenario': 'ESC_\\d{3}',
    'catalogo': 'CAT_\\d{3}',
}

# Configuración de traducción
translation_config = {
    'source_language': 'en',
    'target_language': 'es-MX',
    'preserve_technical_terms': True,
    'first_appearance_format': 'español (:term:`inglés`)',
    'subsequent_format': 'español',
}

# Configuración de biblioteca
library_config = {
    'metadata_private': True,
    'classification_system': 'hierarchical',
    'categories': ['informatica', 'ingenieria', 'ciencias'],
}
